name: 'Build and Deploy'
author: 'Odery'
description: 'Builds the Go binary and deploys it via SSH to remote server.'
inputs:
  ssh-key:
    description: 'SSH for the remote server'
    required: true
  ssh-host:
    description: 'SSH host to connect to'
    required: true
  ssh-user:
    description: 'SSH user for the remote server'
    required: true
  git-sha:
    description: 'Git SHA for metadata'
    required: true
  git-ref:
    description: 'Git branch ref for metadata'
    required: true

runs:
  using: composite
  steps:
    - name: Build Application
      shell: bash
      run: |
        echo "--- 1. Build Application ---"
        go build -ldflags="-X 'main.GitCommitSHA=${{ inputs.git-sha }}' -X 'main.GitBranch=${{ inputs.git-ref }}'" -o artefact ./cmd/PortfolioWebsite

    - name: Configure SSH
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh-key }}
        SSH_HOST: ${{ inputs.ssh-host }}
      run: |
        echo "--- 2. Configure SSH ---"
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
    - name: Deploy Application
      shell: bash
      env:
          SSH_USER: ${{ inputs.ssh-user }}
          SSH_HOST: ${{ inputs.ssh-host }}
      run: |
        echo "--- 3. Deploy Application ---"
        gzip -c artefact | ssh -i ~/.ssh/deploy_key "$SSH_USER"@"$SSH_HOST"
        
        
        
